[package]
name = "select-language-tui"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20"
nom = "^7"
eyre = "0.6"
